apiVersion: apps/v1
kind: Deployment
metadata:
  name: night-scout
spec:
  replicas: 1
  revisionHistoryLimit: 4
  selector:
    matchLabels:
      app: night-scout
  template:
    metadata:
      labels:
        app: night-scout
    spec:
      nodeSelector:
      containers:
      - name: night-scout
        image: registry.explabs.io/personal/nightscout:1555682472
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 300Mi
          limits:
            cpu: 100m
            memory: 300Mi
        ports:
        - containerPort: 1337
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: night-scout
  labels:
    app: night-scout
spec:
  ports:
  - port: 80
    targetPort: 1337
    protocol: TCP
    name: http
  selector:
    app: night-scout
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: night-scout
spec:
  maxReplicas: 1
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: night-scout
  targetCPUUtilizationPercentage: 50